# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'UsingOssTestFramework' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  pod 'Quick'
  pod 'Nimble'

  target 'UsingOssTestFrameworkTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'UsingOssTestFrameworkUITests' do
    # Pods for testing
  end
  
end
